# Generated by Django 4.2 on 2024-02-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_historicaltoyandgames_historicaltoolsandhome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsCatagory',
            fields=[
                ('catagory_type_id', models.IntegerField(db_column='catagory_type_id', primary_key=True, serialize=False, unique=True, verbose_name='CatagoryTypeId')),
                ('catagory_name', models.CharField(max_length=255, unique=True, verbose_name='CatagoryName')),
            ],
        ),
    ]
