# Generated by Django 4.2 on 2024-03-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leadscatagory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='automotiveandindustrial',
            table='leads_automotive_and_industrial',
        ),
    ]
