# Generated by Django 4.2 on 2024-03-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_automotiveandindustrial_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clothingandaccessories',
            table='leads_clothing_and_accessories',
        ),
        migrations.AlterModelTable(
            name='groceryandgourmetfood',
            table='leads_grocery_and_gourmet_food',
        ),
        migrations.AlterModelTable(
            name='healthandbeauty',
            table='leads_health_and_beauty',
        ),
        migrations.AlterModelTable(
            name='homeandkitchen',
            table='leads_home_and_kitchen',
        ),
        migrations.AlterModelTable(
            name='moviesandtv',
            table='leads_movies_and_tv',
        ),
        migrations.AlterModelTable(
            name='officeproducts',
            table='leads_office_product',
        ),
        migrations.AlterModelTable(
            name='petsupplies',
            table='leads_pets_supplies',
        ),
        migrations.AlterModelTable(
            name='softwareandmobileapps',
            table='leads_software_and_mobile_apps',
        ),
        migrations.AlterModelTable(
            name='sportsandoutdoors',
            table='leads_sports_and_outdoors',
        ),
        migrations.AlterModelTable(
            name='toolsandhome',
            table='leads_tools_and_home',
        ),
        migrations.AlterModelTable(
            name='toyandgames',
            table='leads_toy_and_games',
        ),
    ]
