# Generated by Django 4.2 on 2024-03-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_clothingandaccessories_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalautomotiveandindustrial',
            table='history_leads_automotive_and_industrial',
        ),
        migrations.AlterModelTable(
            name='historicalclothingandaccessories',
            table='history_leads_clothing_and_accessories',
        ),
        migrations.AlterModelTable(
            name='historicalgroceryandgourmetfood',
            table='history_leads_grocery_and_gourmet_food',
        ),
        migrations.AlterModelTable(
            name='historicalhealthandbeauty',
            table='history_leads_health_and_beauty',
        ),
        migrations.AlterModelTable(
            name='historicalhomeandkitchen',
            table='history_leads_home_and_kitchen',
        ),
        migrations.AlterModelTable(
            name='historicalmoviesandtv',
            table='history_leads_movies_and_tv',
        ),
        migrations.AlterModelTable(
            name='historicalofficeproducts',
            table='history_leads_office_product',
        ),
        migrations.AlterModelTable(
            name='historicalpetsupplies',
            table='history_leads_pets_supplies',
        ),
        migrations.AlterModelTable(
            name='historicalsoftwareandmobileapps',
            table='history_leads_software_and_mobile_apps',
        ),
        migrations.AlterModelTable(
            name='historicalsportsandoutdoors',
            table='history_leads_sports_and_outdoors',
        ),
        migrations.AlterModelTable(
            name='historicaltoolsandhome',
            table='history_leads_tools_and_home',
        ),
        migrations.AlterModelTable(
            name='historicaltoyandgames',
            table='history_leads_toy_and_games',
        ),
    ]
