# Generated by Django 4.2 on 2024-02-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapi', '0004_alter_leadsdata_number_of_sellers_on_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsdata',
            name='number_of_sellers_on_listing',
            field=models.IntegerField(editable=False, null=True, verbose_name='NumberOfSellersOnListing'),
        ),
    ]
