# Generated by Django 4.2 on 2024-02-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapi', '0012_alter_leadsdata_estimated_monthly_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsdata',
            name='asin',
            field=models.CharField(db_column='asin', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='ASIN'),
        ),
    ]
