# Generated by Django 4.2 on 2024-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapi', '0014_historicalleadsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleadsdata',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='product_name'),
        ),
        migrations.AddField(
            model_name='leadsdata',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='product_name'),
        ),
    ]
