# Generated by Django 4.2.10 on 2024-03-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_rename_leadscatagory_leadscategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadscategory',
            old_name='category_type_id',
            new_name='category_id',
        ),
        migrations.AlterModelTable(
            name='leadscategory',
            table='leads_category',
        ),
    ]
