# Generated by Django 4.2.10 on 2024-03-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_rename_category_type_id_leadscategory_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadscategory',
            old_name='category_id',
            new_name='id',
        ),
    ]
