# Generated by Django 4.2.10 on 2024-03-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_rename_category_id_leadscategory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadscategory',
            old_name='id',
            new_name='category_type_id',
        ),
    ]
