# Generated by Django 4.2.10 on 2024-03-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_rename_id_leadscategory_category_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadscategory',
            name='category_type_id',
            field=models.IntegerField(db_column='category_id', primary_key=True, serialize=False, unique=True, verbose_name='CatagoryTypeId'),
        ),
    ]
