# Generated by Django 4.2.10 on 2024-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_automotiveandindustrial_amazon_fba_estimated_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotiveandindustrial',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='automotiveandindustrial',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='automotiveandindustrial',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='automotiveandindustrial',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='automotiveandindustrial',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='automotiveandindustrial',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='automotiveandindustrial',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='books',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='books',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='books',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='books',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='books',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='books',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='books',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='clothingandaccessories',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='clothingandaccessories',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='clothingandaccessories',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='clothingandaccessories',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='clothingandaccessories',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='clothingandaccessories',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='clothingandaccessories',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='groceryandgourmetfood',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='groceryandgourmetfood',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='groceryandgourmetfood',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='groceryandgourmetfood',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='groceryandgourmetfood',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='groceryandgourmetfood',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='groceryandgourmetfood',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='healthandbeauty',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='healthandbeauty',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='healthandbeauty',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='healthandbeauty',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='healthandbeauty',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='healthandbeauty',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='healthandbeauty',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalautomotiveandindustrial',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalautomotiveandindustrial',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalautomotiveandindustrial',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalautomotiveandindustrial',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalautomotiveandindustrial',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalautomotiveandindustrial',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalautomotiveandindustrial',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalbooks',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalbooks',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalbooks',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalbooks',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalbooks',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalbooks',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalbooks',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalclothingandaccessories',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalclothingandaccessories',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalclothingandaccessories',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalclothingandaccessories',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalclothingandaccessories',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalclothingandaccessories',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalclothingandaccessories',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalelectronics',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalelectronics',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalelectronics',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalelectronics',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalelectronics',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalelectronics',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalelectronics',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalgroceryandgourmetfood',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalgroceryandgourmetfood',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalgroceryandgourmetfood',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalgroceryandgourmetfood',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalgroceryandgourmetfood',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalgroceryandgourmetfood',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalgroceryandgourmetfood',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalhealthandbeauty',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalhealthandbeauty',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalhealthandbeauty',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalhealthandbeauty',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalhealthandbeauty',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalhealthandbeauty',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalhealthandbeauty',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalhomeandkitchen',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalhomeandkitchen',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalhomeandkitchen',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalhomeandkitchen',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalhomeandkitchen',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalhomeandkitchen',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalhomeandkitchen',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalmoviesandtv',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalmoviesandtv',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalmoviesandtv',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalmoviesandtv',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalmoviesandtv',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalmoviesandtv',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalmoviesandtv',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalofficeproducts',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalofficeproducts',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalofficeproducts',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalofficeproducts',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalofficeproducts',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalofficeproducts',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalofficeproducts',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalpetsupplies',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalpetsupplies',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalpetsupplies',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalpetsupplies',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalpetsupplies',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalpetsupplies',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalpetsupplies',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalsoftwareandmobileapps',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalsoftwareandmobileapps',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalsoftwareandmobileapps',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalsoftwareandmobileapps',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalsoftwareandmobileapps',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalsoftwareandmobileapps',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalsoftwareandmobileapps',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicalsportsandoutdoors',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicalsportsandoutdoors',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicalsportsandoutdoors',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicalsportsandoutdoors',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalsportsandoutdoors',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicalsportsandoutdoors',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicalsportsandoutdoors',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicaltoolsandhome',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicaltoolsandhome',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicaltoolsandhome',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicaltoolsandhome',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicaltoolsandhome',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicaltoolsandhome',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicaltoolsandhome',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='historicaltoyandgames',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='historicaltoyandgames',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='historicaltoyandgames',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='historicaltoyandgames',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicaltoyandgames',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='historicaltoyandgames',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='historicaltoyandgames',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='homeandkitchen',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='homeandkitchen',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='homeandkitchen',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='homeandkitchen',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='homeandkitchen',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='homeandkitchen',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='homeandkitchen',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='moviesandtv',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='moviesandtv',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='moviesandtv',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='moviesandtv',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='moviesandtv',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='moviesandtv',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='moviesandtv',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='officeproducts',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='officeproducts',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='officeproducts',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='officeproducts',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='officeproducts',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='officeproducts',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='officeproducts',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='petsupplies',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='petsupplies',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='petsupplies',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='petsupplies',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='petsupplies',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='petsupplies',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='petsupplies',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='softwareandmobileapps',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='softwareandmobileapps',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='softwareandmobileapps',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='softwareandmobileapps',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='softwareandmobileapps',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='softwareandmobileapps',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='softwareandmobileapps',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='sportsandoutdoors',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='sportsandoutdoors',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='sportsandoutdoors',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='sportsandoutdoors',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='sportsandoutdoors',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='sportsandoutdoors',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='sportsandoutdoors',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='toolsandhome',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='toolsandhome',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='toolsandhome',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='toolsandhome',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='toolsandhome',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='toolsandhome',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='toolsandhome',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
        migrations.AlterField(
            model_name='toyandgames',
            name='amazon_fba_estimated_fees',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonFBAEstimatedFees'),
        ),
        migrations.AlterField(
            model_name='toyandgames',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='AmazonPrice'),
        ),
        migrations.AlterField(
            model_name='toyandgames',
            name='estimated_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfit'),
        ),
        migrations.AlterField(
            model_name='toyandgames',
            name='estimated_gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedGrossProfitMargin'),
        ),
        migrations.AlterField(
            model_name='toyandgames',
            name='estimated_net_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfit'),
        ),
        migrations.AlterField(
            model_name='toyandgames',
            name='estimated_net_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='EstimatedNetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='toyandgames',
            name='sourcing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='SourcingPrice'),
        ),
    ]
