# Generated by Django 4.2 on 2024-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapi', '0003_alter_leadsdata_estimated_monthly_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsdata',
            name='number_of_sellers_on_listing',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='NumberOfSellersOnListing'),
        ),
    ]
