# Generated by Django 4.2 on 2024-02-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapi', '0010_alter_leadsdata_number_of_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsdata',
            name='estimated_sales_rank',
            field=models.PositiveIntegerField(default=0, verbose_name='EstimatedSalesRank'),
        ),
    ]
