# Generated by Django 4.2 on 2024-02-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapi', '0011_alter_leadsdata_estimated_sales_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsdata',
            name='estimated_monthly_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='EstimatedMonthlySales'),
        ),
        migrations.AlterField(
            model_name='leadsdata',
            name='number_of_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='NumberOfReviews'),
        ),
        migrations.AlterField(
            model_name='leadsdata',
            name='number_of_sellers_on_listing',
            field=models.PositiveIntegerField(default=0, verbose_name='NumberOfSellersOnListing'),
        ),
        migrations.AlterField(
            model_name='leadsdata',
            name='sales_rank_30_days',
            field=models.PositiveIntegerField(default=0, verbose_name='SalesRank30Days'),
        ),
        migrations.AlterField(
            model_name='leadsdata',
            name='sales_rank_90_days',
            field=models.PositiveIntegerField(default=0, verbose_name='SalesRank90Days'),
        ),
    ]
