# Generated by Django 4.2 on 2024-02-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapi', '0017_electronics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeAndKitchen',
        ),
    ]
